kind: pipeline
name: default

steps:
  - name: bake
    image: plugins/docker
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      repo: rubasace/vue-hello-world
#      registry: registry.nasvigo.com/v2
      tags: 1.0.0.${CI_BUILD_NUMBER}
      debug: true
    when:
      branch:
        - master
  - name: deploy
    image: rubasace/drone-k8s
    environment:
      K8S_CERT_AUTHORITY_DATA:
        from_secret: K8S_CERT_AUTHORITY_DATA
      K8S_SERVER:
        from_secret: K8S_SERVER
      K8S_USER:
        from_secret: K8S_USER
      K8S_PASSWORD:
        from_secret: K8S_PASSWORD
      DOMAIN: nasvigo.com
      NAMESPACE: production
      SUBDOMAIN: hello
      PULL_SECRET: regcred
      DOCKER_REGISTRY: rubasace
    when:
      branch:
        - master